## Summary: Three ways to do SVD in python  
**The first is for normal matrix SVD using numpy.linalg;
The second and the third is specially for sparse SVD.   
There are 2 differences between the second and the third:   
1) the second's singular values are in increasing order while the third's are in descending order.  
2) The left singular vector of the seocnd is the transpose of the third one.**

In [1]:
from __future__ import division
import numpy as np
import random
from numpy import linalg as la
from sparsesvd import sparsesvd
from scipy.sparse.linalg import norm
import scipy.sparse as ss
import scipy.io
import random

### Parameter Setting
- n1,n2 are row number and col number of a random Matrix respectively
- m is the scale of sampeling
- Omega is the sample space
- P_Omega_M is the sparse matrix we need to decompose with

In [2]:
n1, n2, r = 150, 300, 10
m = r*(n1+n2-r);
M = np.random.random((n1,r)).dot(np.random.random((r,n2)))
ind = random.sample(range(n1*n2),m)
Omega = np.unravel_index(ind, (n1,n2))
data = M[Omega]
P_Omega_M = ss.csr_matrix((data,Omega),shape = (n1,n2))

In [3]:
# 1st
U,s,V = la.svd(M)
print (U.shape,s.shape,V.shape)
S = np.zeros(M.shape)
index = s.shape[0]
S[:index, :index] = np.diag(s)
np.dot(U,np.dot(S,V))

(150, 150) (150,) (300, 300)


array([[3.52586193, 3.72613913, 4.04847872, ..., 3.26770844, 3.14296316,
        2.7044627 ],
       [2.11504979, 2.16329274, 2.99696294, ..., 2.49245926, 2.04143089,
        2.08976289],
       [2.39812552, 2.75888171, 3.12933592, ..., 2.90851031, 1.96067128,
        2.10516137],
       ...,
       [2.79861816, 3.32616636, 3.19874329, ..., 2.55913735, 2.75948708,
        2.06194095],
       [2.4423569 , 2.82182227, 2.81257629, ..., 1.48163053, 2.16153512,
        1.92823386],
       [1.39203038, 1.39700846, 1.47176637, ..., 1.78278154, 1.37685712,
        0.91925431]])

In [4]:
# 2nd
u1,s1,v1 = ss.linalg.svds(P_Omega_M,6)
print (u1.shape,s1.shape,v1.shape)
print (s1)
(u1*s1).dot(v1)

(150, 6) (6,) (6, 300)
[ 39.66096567  40.86065823  41.46498624  42.05543051  42.67869924
 275.05774197]


array([[2.40260114, 0.86144163, 1.93841812, ..., 2.1119544 , 1.64124341,
        2.00495237],
       [0.94036674, 1.50836185, 1.07327024, ..., 1.00010048, 0.85490759,
        0.85429256],
       [1.43914915, 1.38559485, 1.29759542, ..., 1.07552284, 0.86844104,
        1.41718054],
       ...,
       [1.07300815, 1.83437428, 0.78209937, ..., 1.00152197, 1.27255597,
        1.31871913],
       [0.85647968, 1.34650564, 0.65940981, ..., 0.90650253, 0.98641336,
        1.0504069 ],
       [0.83541829, 0.76286011, 0.77417648, ..., 0.77262491, 0.58710677,
        0.80988788]])

In [5]:
# 3rd
ut, s, vt = sparsesvd(ss.csc_matrix(P_Omega_M),6)
print (ut.shape,s.shape,vt.shape)
print (s)
(ut.T*s).dot(vt)

(6, 150) (6,) (6, 300)
[275.05774197  42.67869924  42.05543051  41.46498624  40.86065823
  39.66096567]


array([[2.40260114, 0.86144163, 1.93841812, ..., 2.1119544 , 1.64124341,
        2.00495237],
       [0.94036674, 1.50836185, 1.07327024, ..., 1.00010048, 0.85490759,
        0.85429256],
       [1.43914915, 1.38559485, 1.29759542, ..., 1.07552284, 0.86844104,
        1.41718054],
       ...,
       [1.07300815, 1.83437428, 0.78209937, ..., 1.00152197, 1.27255597,
        1.31871913],
       [0.85647968, 1.34650564, 0.65940981, ..., 0.90650253, 0.98641336,
        1.0504069 ],
       [0.83541829, 0.76286011, 0.77417648, ..., 0.77262491, 0.58710677,
        0.80988788]])